spring:
  cloud:
    config:
      server:
        git:
          password:
          searchPaths: xm-skeleton
          uri: https://github.com/weison-tech/spring-cloud-config-server.git
          username:
      label: master
  application:
    name: config-server
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/